"""
High-quality translation dictionary and rule engine for fitness exercise instructions.
Maps Dutch fitness sentences and idioms to natural, idiomatic fitness English.
"""

import re

# Comprehensive Dutch to English fitness translation dictionary
DICTIONARY = [
    # Complex phrases & patterns
    (r'(?i)\bde basisoefening\b', 'The fundamental base exercise.'),
    (r'(?i)\bde basis squat zonder gewicht\b', 'The foundational bodyweight squat.'),
    (r'(?i)\bideaal om de techniek te leren en je bereik langzaam te vergroten\b', 'Ideal for learning proper technique and progressively increasing range of motion.'),
    (r'(?i)\bzeer zwaar en alleen voor gevorderden\b', 'Very demanding and recommended for advanced athletes only.'),
    (r'(?i)\bdit legt de focus op de schuine buikspieren\b', 'This emphasizes the oblique muscles.'),
    (r'(?i)\bextreem zwaar voor anti-rotatie\b', 'Extremely challenging for core anti-rotational stability.'),
    (r'(?i)\bhoud je lichaam als een plank\b', 'maintain a rigid, straight plank line from head to heels'),
    (r'(?i)\bhoud je lichaam als een rechte plank\b', 'maintain a rigid, straight plank line from head to heels'),
    (r'(?i)\bhoud het lichaam als een plank\b', 'maintain a rigid, straight plank line from head to heels'),
    (r'(?i)\bhoud je rug recht en borst op\b', 'keep your back straight and chest proud'),
    (r'(?i)\bhoud de rug recht\b', 'keep your spine flat and neutral'),
    (r'(?i)\bhoud je rug recht\b', 'keep your spine flat and neutral'),
    (r'(?i)\bspan de onderrug en billen aan\b', 'contract your lower back and squeeze your glutes'),
    (r'(?i)\bspan je buikspieren en bilspieren goed aan\b', 'brace your core and squeeze your glutes firmly'),
    (r'(?i)\bspan je buikspieren maximaal aan\b', 'brace your abdominals with maximum tension'),
    (r'(?i)\blaat het gewicht gecontroleerd zakken\b', 'lower the weight in a smooth, controlled motion'),
    (r'(?i)\bduw krachtig uit vanuit je hielen\b', 'drive up powerfully through your heels'),
    (r'(?i)\badem in bij het zakken, blaas uit bij het omhoog komen\b', 'inhale as you descend, and exhale forcefully as you drive upward'),
    (r'(?i)\bhoud de spanning constant op de spieren\b', 'maintain continuous muscular tension throughout the rep'),
    (r'(?i)\bwissel om en om van kant\b', 'alternate sides with each repetition'),
    (r'(?i)\bherhaal voor het gewenste aantal herhalingen\b', 'repeat for the prescribed number of repetitions'),
    (r'(?i)\bland zachtjes op de bal van je voeten\b', 'land softly on the balls of your feet absorbing the impact'),
    (r'(?i)\bhoud je ellebogen dicht bij je lichaam\b', 'keep your elbows tucked close to your ribcage'),
    (r'(?i)\bkijk recht vooruit en houd je nek neutraal\b', 'look straight ahead and keep your neck in a neutral alignment'),
    (r'(?i)\bbeweeg vanuit de heupen en niet vanuit de onderrug\b', 'hinge from your hips rather than rounding your lower back'),

    # Position setups
    (r'(?i)\bzit op je knieën\b', 'Kneel on the floor or exercise mat'),
    (r'(?i)\bsta rechtop\b', 'Stand tall with good posture'),
    (r'(?i)\bga op de bank liggen\b', 'Lie flat on the bench'),
    (r'(?i)\bga op je rug liggen\b', 'Lie flat on your back'),
    (r'(?i)\blig op je rug\b', 'Lie flat on your back'),
    (r'(?i)\blig op de buik\b', 'Lie prone on your stomach'),
    (r'(?i)\bneem een plankpositie aan\b', 'Assume a strong plank position'),
    (r'(?i)\bstart in (een )?plankpositie\b', 'Start in a full plank position'),
    (r'(?i)\bstart in (een )?push-up positie\b', 'Start in a push-up position'),
    (r'(?i)\bstart staand\b', 'Start in an upright standing position'),
    (r'(?i)\bsta op heupbreedte\b', 'Stand with feet hip-width apart'),
    (r'(?i)\bsta op schouderbreedte\b', 'Stand with feet shoulder-width apart'),
    (r'(?i)\bvoeten op heupbreedte\b', 'feet positioned hip-width apart'),
    (r'(?i)\bvoeten op schouderbreedte\b', 'feet positioned shoulder-width apart'),
    (r'(?i)\bpak de stang vast\b', 'grip the barbell firmly'),
    (r'(?i)\bpak de stang iets breder dan schouderbreedte\b', 'grip the barbell slightly wider than shoulder-width'),
    (r'(?i)\bpak de dumbbells vast\b', 'grip the dumbbells firmly'),
    (r'(?i)\bpak de handvatten vast\b', 'grasp the handles firmly'),
    (r'(?i)\bpak beide uiteinden\b', 'grasp both rope ends'),
    (r'(?i)\bhang aan de stang\b', 'hang from the bar with arms fully extended'),
    (r'(?i)\bplaats je handen\b', 'place your hands'),
    (r'(?i)\bplaats je voeten\b', 'place your feet'),
    (r'(?i)\bklem de banden onder je oksels\b', 'secure the straps under your armpits'),

    # Executions
    (r'(?i)\brol het wiel gecontroleerd naar voren\b', 'roll the wheel forward with control'),
    (r'(?i)\btot je lichaam bijna gestrekt is\b', 'until your torso and hips are almost fully extended'),
    (r'(?i)\btrek jezelf vanuit je buikspieren weer terug\b', 'contract your abdominals to pull yourself back'),
    (r'(?i)\bnaar de startpositie\b', 'to the starting position'),
    (r'(?i)\brol richting een muur\b', 'roll toward a wall'),
    (r'(?i)\bde muur dient als stopblok zodat je niet te ver gaat\b', 'the wall serves as a safety stop to prevent overextending'),
    (r'(?i)\bde instabiliteit van het wiel maakt de plank veel zwaarder\b', 'the wheel instability significantly amplifies core challenge'),
    (r'(?i)\bbuig voorover en rol het wiel uit tot je volledig gestrekt boven de grond zweeft\b', 'hinge forward and roll out until hovering fully extended above the floor'),
    (r'(?i)\btrek jezelf weer omhoog tot stand\b', 'pull yourself back up into a full standing position'),
    (r'(?i)\btrek vanuit een plankpositie je knieën naar je borst\b', 'from a plank position, drive your knees toward your chest'),
    (r'(?i)\brol gecontroleerd terug naar plank\b', 'roll smoothly back into the starting plank'),
    (r'(?i)\blaad de stang gecontroleerd zakken\b', 'lower the barbell in a controlled descent'),
    (r'(?i)\blaat de stang gecontroleerd zakken\b', 'lower the barbell in a controlled descent'),
    (r'(?i)\btot het midden van je borst\b', 'down to the midpoint of your chest'),
    (r'(?i)\bduw krachtig uit tot je armen gestrekt zijn\b', 'press forcefully upward until your arms reach full extension'),
    (r'(?i)\bleg de stang in je nek\b', 'rest the barbell across your upper trapezius'),
    (r'(?i)\bzak door je knieën en heupen alsof je gaat zitten\b', 'hinge at your hips and bend your knees as if sitting into a chair'),
    (r'(?i)\bhoud je rug recht en kom weer omhoog\b', 'keep your back straight and drive back up to standing'),
    (r'(?i)\bsta met je schenen tegen de stang\b', 'stand with your shins touching the barbell'),
    (r'(?i)\btil de stang op door je benen te strekken en je heupen naar voren te duwen\b', 'lift the bar by extending your legs and driving your hips forward into full lockout'),
    (r'(?i)\bhoud de stang op borsthoogte\b', 'hold the barbell at shoulder/collarbone height'),
    (r'(?i)\bduw de stang recht omhoog tot boven je hoofd\b', 'press the barbell straight overhead to full extension'),
    (r'(?i)\bspan je buikspieren aan en leun niet te ver naar achteren\b', 'brace your core and avoid arching your lower back'),
    (r'(?i)\bbuig voorover vanuit de heupen\b', 'hinge forward at the hips maintaining a flat back'),
    (r'(?i)\btrek de stang naar je navel\b', 'row the barbell toward your belly button'),
    (r'(?i)\bknijp je schouderbladen samen\b', 'squeeze your shoulderblades firmly together'),
    (r'(?i)\bspring explosief omhoog\b', 'jump up explosively'),
    (r'(?i)\bland zachtjes op de box\b', 'land softly on top of the plyo box'),
    (r'(?i)\bstap gecontroleerd naar beneden\b', 'step down carefully one foot at a time'),
    (r'(?i)\btrek jezelf op tot je kin boven de stang is\b', 'pull yourself up until your chin clears the bar'),
    (r'(?i)\blaat jezelf rustig zakken tot volledige stretch\b', 'lower yourself under control to a full dead hang stretch'),
    (r'(?i)\bsla ze tegelijk hard op de grond\b', 'slam both ropes powerfully into the ground simultaneously'),
    (r'(?i)\bmaak golven om en om met links en rechts\b', 'alternate rapid dynamic waves between left and right arms'),
    (r'(?i)\bhoud het tempo hoog\b', 'maintain a high tempo and intensity'),
    (r'(?i)\bloop op handen en voeten\b', 'crawl on hands and feet with knees hovering just above the floor'),
    (r'(?i)\bhoud de heupen laag en de rug recht\b', 'keep hips low and back flat like a tabletop'),
    (r'(?i)\bduw de slee krachtig naar voren\b', 'drive the sled forward with powerful leg strides'),
    (r'(?i)\btrek de slee achterwaarts\b', 'drag the sled walking backward with upright torso'),

    # Words & short phrases
    (r'(?i)\bin plaats van op de grond\b', 'instead of on the floor'),
    (r'(?i)\bin plaats van\b', 'instead of'),
    (r'(?i)\bnaar links en bij de volgende herhaling naar rechts\b', 'to the left, then to the right on the next repetition'),
    (r'(?i)\bdiagonaal naar buiten, wisselend tussen links en rechts in een \'V\' vorm\b', 'diagonally outward, alternating left and right in a V-shape'),
    (r'(?i)\bmet voetsteunen\b', 'with foot straps'),
    (r'(?i)\bvoor anti-rotatie\b', 'for anti-rotation'),
    (r'(?i)\bom en om snel naar je borst\b', 'alternating rapidly toward your chest'),
    (r'(?i)\bop handen en voeten \(niet knieën!\)\b', 'on hands and balls of feet (keep knees off the ground!)'),
    (r'(?i)\bknijp de billen samen\b', 'squeeze your glutes together'),
    (r'(?i)\bzonder gewicht\b', 'bodyweight only'),
    (r'(?i)\bzakken tot de bovenbenen parallel zijn\b', 'lower down until thighs are parallel to the floor'),
    (r'(?i)\btil benen en borst tegelijk van de grond\b', 'lift legs and chest off the ground simultaneously'),
    (r'(?i)\bloop op je handen naar voren\b', 'walk forward on your hands'),
    (r'(?i)\bhet wiel volgt je voeten\b', 'the wheel rolls behind following your feet'),
    (r'(?i)\bdit vergt enorme stabilisatie van de core\b', 'this requires significant core stabilization'),
    (r'(?i)\bknieën\b', 'knees'), (r'(?i)\bknie\b', 'knee'),
    (r'(?i)\bvoeten\b', 'feet'), (r'(?i)\bvoet\b', 'foot'),
    (r'(?i)\bhanden\b', 'hands'), (r'(?i)\bhand\b', 'hand'),
    (r'(?i)\barmen\b', 'arms'), (r'(?i)\barm\b', 'arm'),
    (r'(?i)\bbenen\b', 'legs'), (r'(?i)\bbeen\b', 'leg'),
    (r'(?i)\bborst\b', 'chest'), (r'(?i)\brug\b', 'back'),
    (r'(?i)\bschouders\b', 'shoulders'), (r'(?i)\bschouder\b', 'shoulder'),
    (r'(?i)\bheupen\b', 'hips'), (r'(?i)\bheup\b', 'hip'),
    (r'(?i)\bbillen\b', 'glutes'), (r'(?i)\bbuikspieren\b', 'abdominals'),
    (r'(?i)\bbuik\b', 'abdominals'), (r'(?i)\bellebogen\b', 'elbows'),
    (r'(?i)\belleboog\b', 'elbow'), (r'(?i)\bschenen\b', 'shins'),
    (r'(?i)\bhielen\b', 'heels'), (r'(?i)\btenen\b', 'toes'),
    (r'(?i)\bhoofd\b', 'head'), (r'(?i)\bkin\b', 'chin'),
    (r'(?i)\bnavel\b', 'belly button'),
    (r'(?i)\bgecontroleerd\b', 'controlled'), (r'(?i)\bgestrekt\b', 'extended'),
    (r'(?i)\bgebogen\b', 'bent'), (r'(?i)\bexplosief\b', 'explosively'),
    (r'(?i)\blangzaam\b', 'slowly'), (r'(?i)\bkrachtig\b', 'powerfully'),
    (r'(?i)\bsnel\b', 'quickly'), (r'(?i)\brustig\b', 'smoothly'),
    (r'(?i)\bomhoog\b', 'upward'), (r'(?i)\bomlaag\b', 'downward'),
    (r'(?i)\bnaar voren\b', 'forward'), (r'(?i)\bnaar achteren\b', 'backward'),
    (r'(?i)\bnaar buiten\b', 'outward'), (r'(?i)\bnaar binnen\b', 'inward'),
    (r'(?i)\bnaar de grond\b', 'to the ground'), (r'(?i)\bvan de grond\b', 'off the ground'),
    (r'(?i)\bzijwaarts\b', 'laterally'), (r'(?i)\btegelijk\b', 'simultaneously'),
    (r'(?i)\bafwisselend\b', 'alternating'), (r'(?i)\bwisselend\b', 'alternating'),
    (r'(?i)\bom en om\b', 'in an alternating rhythm'),
    (r'(?i)\bherhaling\b', 'repetition'), (r'(?i)\bherhalingen\b', 'repetitions'),
    (r'(?i)\bstartpositie\b', 'starting position'), (r'(?i)\bhouding\b', 'posture'),
    (r'(?i)\bweerstand\b', 'resistance'), (r'(?i)\bgewicht\b', 'weight'),
    (r'(?i)\bgewichten\b', 'weights'), (r'(?i)\bstang\b', 'barbell'),
    (r'(?i)\bhalter\b', 'dumbbell'), (r'(?i)\bhalters\b', 'dumbbells'),
    (r'(?i)\bkogel\b', 'kettlebell'), (r'(?i)\btouw\b', 'rope'),
    (r'(?i)\btouwen\b', 'ropes'), (r'(?i)\bband\b', 'resistance band'),
    (r'(?i)\bbanden\b', 'resistance bands'), (r'(?i)\bmuur\b', 'wall'),
    (r'(?i)\bvloer\b', 'floor'), (r'(?i)\bgrond\b', 'ground'),
    (r'(?i)\bbank\b', 'bench'), (r'(?i)\bmat\b', 'mat'),
    (r'(?i)\blinks\b', 'left'), (r'(?i)\brechts\b', 'right'),
    (r'(?i)\ben\b', 'and'), (r'(?i)\bof\b', 'or'),
    (r'(?i)\bmet\b', 'with'), (r'(?i)\bvan\b', 'of'),
    (r'(?i)\bnaar\b', 'to'), (r'(?i)\bvoor\b', 'for'),
    (r'(?i)\bop\b', 'on'), (r'(?i)\bin\b', 'in'),
    (r'(?i)\baan\b', 'at'), (r'(?i)\bbij\b', 'at'),
    (r'(?i)\bom\b', 'to'), (r'(?i)\bdoor\b', 'through'),
    (r'(?i)\bte\b', 'to'), (r'(?i)\btot\b', 'until'),
    (r'(?i)\bals\b', 'as'), (r'(?i)\bniet\b', 'not'),
    (r'(?i)\book\b', 'also'), (r'(?i)\bmaar\b', 'but'),
    (r'(?i)\bover\b', 'over'), (r'(?i)\buit\b', 'out'),
    (r'(?i)\bzo\b', 'so'), (r'(?i)\bweer\b', 'again'),
    (r'(?i)\bterwijl\b', 'while'), (r'(?i)\bzodat\b', 'so that'),
    (r'(?i)\bwaar\b', 'where'), (r'(?i)\bdeze\b', 'this'),
    (r'(?i)\bdit\b', 'this'), (r'(?i)\bdat\b', 'that'),
    (r'(?i)\bdie\b', 'that'), (r'(?i)\belk\b', 'each'),
    (r'(?i)\belke\b', 'every'), (r'(?i)\bsteeds\b', 'constantly'),
    (r'(?i)\bhoud\b', 'keep'), (r'(?i)\bzorg\b', 'ensure'),
    (r'(?i)\bplaats\b', 'place'), (r'(?i)\bbreng\b', 'bring'),
    (r'(?i)\bzak\b', 'lower'), (r'(?i)\bduw\b', 'push'),
    (r'(?i)\btrek\b', 'pull'), (r'(?i)\btil\b', 'lift'),
    (r'(?i)\bspring\b', 'jump'), (r'(?i)\bloop\b', 'walk'),
    (r'(?i)\bde\b', 'the'), (r'(?i)\bhet\b', 'the'),
    (r'(?i)\been\b', 'a'), (r'(?i)\bje\b', 'your'),
    (r'(?i)\bjou\b', 'your'), (r'(?i)\bjezelf\b', 'yourself'),
    (r'(?i)\bspan\b', 'brace'), (r'(?i)\bknijp\b', 'squeeze'),
    (r'(?i)\bdraai\b', 'rotate'), (r'(?i)\bstoot\b', 'strike'),
    (r'(?i)\btrap\b', 'kick'), (r'(?i)\bvang\b', 'catch'),
    (r'(?i)\bwerp\b', 'throw'), (r'(?i)\bgooi\b', 'throw')
]

def translate_dutch_sentence(text):
    text = text.strip()
    if not text:
        return ""
    res = text
    for pat, repl in DICTIONARY:
        res = re.sub(pat, repl, res)
    
    # Format and clean punctuation
    res = re.sub(r'\s+', ' ', res).strip()
    res = re.sub(r'\.+', '.', res)
    if res:
        res = res[0].upper() + res[1:]
        if not res.endswith(('.', '!', '?')):
            res += '.'
    return res
